"""
Moltbook-Clone — Orchestrator
Runs the Interaction Engine → Evaluation Pipeline → exports results.

Usage:
  python main.py                 # Full run (calls Anthropic API)
  python main.py --dry-run       # Uses sample_output.json (no API calls)
  python main.py --threads 3     # Override number of threads
"""

import argparse
import json
import os
import sys

from dotenv import load_dotenv

load_dotenv()  # Load .env before importing modules that read env vars

from config import NUM_THREADS, OUTPUT_JSON, OUTPUT_JS, SAMPLE_PATH
from interaction_engine import create_client, generate_thread
from evaluation import score_response, evaluate_threads


# ── Helpers ───────────────────────────────────────────────────────────────────

def save_results(results: dict) -> None:
    """Write results as JSON and as a JS module for the frontend."""
    os.makedirs(os.path.dirname(OUTPUT_JSON), exist_ok=True)

    with open(OUTPUT_JSON, "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2, ensure_ascii=False)

    with open(OUTPUT_JS, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by main.py — do not edit manually\n")
        fh.write("var MOLTBOOK_DATA = ")
        json.dump(results, fh, indent=2, ensure_ascii=False)
        fh.write(";\n")

    print(f"  Saved → {OUTPUT_JSON}")
    print(f"  Saved → {OUTPUT_JS}")


def print_summary(results: dict) -> None:
    bar = "─" * 52
    print(f"\n{bar}")
    print(f"  MOLTBOOK EVALUATION RESULTS")
    print(bar)
    for model, avg in results["model_averages"].items():
        tag = "  ★ WINNER" if model == results["winner"] else ""
        print(f"  {model}{tag}")
        print(f"    avg score: {avg:.2f}")
    print(bar)
    print(f"\n  Open frontend/index.html in your browser to view results.")
    print()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Moltbook-Clone: LLM/SLM Evaluation Framework for Skincare"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Load sample_output.json instead of calling the API",
    )
    parser.add_argument(
        "--threads", type=int, default=NUM_THREADS,
        help=f"Number of conversation threads to generate (default: {NUM_THREADS})",
    )
    args = parser.parse_args()

    # ── Dry-run mode ──────────────────────────────────────────────────────────
    if args.dry_run:
        print("Dry-run mode — loading sample data (no API calls).\n")
        if not os.path.exists(SAMPLE_PATH):
            print(f"ERROR: {SAMPLE_PATH} not found.", file=sys.stderr)
            sys.exit(1)
        with open(SAMPLE_PATH, encoding="utf-8") as fh:
            results = json.load(fh)
        print(f"  Loaded {len(results['threads'])} threads from {SAMPLE_PATH}")
        save_results(results)
        print_summary(results)
        return

    # ── Full run ──────────────────────────────────────────────────────────────
    print(f"Moltbook-Clone | threads: {args.threads}\n")

    try:
        client = create_client()
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    threads = []
    for i in range(1, args.threads + 1):
        print(f"[{i}/{args.threads}] Generating thread...", end=" ", flush=True)
        try:
            thread = generate_thread(client, i)
        except Exception as exc:  # noqa: BLE001
            print(f"\nERROR on thread {i}: {exc}", file=sys.stderr)
            sys.exit(1)

        print("→ Evaluating...", end=" ", flush=True)
        score_result = score_response(thread["answer_text"])
        print(f"→ Score: {score_result['total_score']:.1f}")
        threads.append(thread)

    print("\nFinalising evaluation...")
    results = evaluate_threads(threads)
    save_results(results)
    print_summary(results)


if __name__ == "__main__":
    main()
